### ISSUE TITLE
Migrate off Travis CI

### ISSUE THREAD

**Issue by eddiezane** [eddiezane/sendgrid-actionmailer#104]
This project currently uses TravisCi.org which was supposed to [shut down end of 2020](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D).

Probably a good idea to migrate to GitHub actions.

@tyrauber any thoughts?

**Comment by tyrauber** [comment]
Yep, sounds like a good idea. Something like [feature/github_actions](https://github.com/eddiezane/sendgrid-actionmailer/blob/feature/github_actions/actions.yml) should work.
