### ISSUE TITLE
Can't send any emails

### ISSUE THREAD

**Issue by jcohenho** [eddiezane/sendgrid-actionmailer#16]
I've created an API key in my sendgrid dashboard and have added:

```
config.action_mailer.delivery_method = :sendgrid_actionmailer
  config.action_mailer.sendgrid_actionmailer_settings = {
    api_key: ENV['SENDGRID_API_KEY']
  }
```
to production.rb. Sending an email with a UserMailer class in console generates:

```
UserMailer#launch_email: processed outbound mail in 7.7ms
=> #<Mail::Message:70117088042780, Multipart: false, Headers: <From: foo@bar.com>, <To: bar@foo.com>, <Subject: test!>, <Mime-Version: 1.0>, <Content-Type: text/html>>
```

However nothing ever arrives in my inbox, and sendgrid dashboard doesn't show any activity for an outbound email. Any other settings I'm forgetting to include?

**Comment by GUI** [comment]
Hm, I'm not exactly sure about this, but a few thoughts:

- Is there any error output in `log/production.log`?
- Is `ENV['SENDGRID_API_KEY']` set within the your console where you were running the command?
- Have you set `config.action_mailer.raise_delivery_errors = false` in your `config/environments/production.rb` or `config/application.rb`?

**Comment by jcohenho** [comment]
😵 Fail. I forgot how to use ActionMailer and didn't use deliver_now or deliver_later following mail creation. Works great now, thanks!
