### ISSUE TITLE
Devise

### ISSUE THREAD

**Issue by RichardGrossman** [eddiezane/sendgrid-actionmailer#18]
Can you add doc for the steps needed to make this work with Devise?

**Comment by RichardGrossman** [comment]
I see you are not actively supporting this gem - it's for an old version of Ruby.  Can you say that somewhere in your doc or else remove it from Github?  There are links to it elsewhere and it's a deadend and time waster.

**Comment by eddiezane** [comment]
Pull requests are welcome, sir.
