### ISSUE TITLE
Incompatibility with new SendGrid API (v3)

### ISSUE THREAD

**Issue by rossettistone** [eddiezane/sendgrid-actionmailer#21]
Using this gem, I've been getting intermittent "Could not authenticate" errors from SendGrid when trying to send emails. As they're intermittent, I've been having trouble getting to the root cause, but I did run across this note in SendGrid's docs:

"API Keys work for v3 API calls and for sending email. API endpoints prior to v3 do not support API keys at this time." - https://sendgrid.com/docs/Classroom/Send/How_Emails_Are_Sent/api_keys.html

As this gem's `gemspec` limits the `sendgrid-ruby` version to `< 2.0`, it seems that we're not using SendGrid's v3 API, which leads me to wonder if this is a cause of the issue.

For the moment, given project time constraints, I'm planning to use a different approach to integrating with SendGrid, but wanted to file this issue in the hopes that it's helpful.

Thanks for your work in creating this!

**Comment by MxBird** [comment]
@rossettistone did you have any way to integrating with SendGrid API V3 in RoR project.  I'm in the the same situation

**Comment by eddiezane** [comment]
Not sure when I'll have time to upgrade the inner workings but if someone is look to become a contributor you'd just need to swap in the [new version](https://github.com/sendgrid/sendgrid-ruby#with-mail-helper-class) of the library [here](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb).

**Comment by rossettistone** [comment]
Thanks, @eddiezane. Should I have some slack, I'll take a swing at contributing!

@MxBird Sendgrid has decent docs on Rails integration here: https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html

I can't find the docs on using an API key specifically (they're around here somewhere...), but I think it's pretty much the same as the general Rails docs, except replace `username` with `'apikey'`, then use the API key string as the `password`.

Best o' luck!

**Comment by eddiezane** [comment]
To clarify - this library integrates SendGrid's HTTP API with ActionMailer.

You can use plain old ActionMailer to work with SMTP out of the box. One of the reasons you might want to go through the HTTP API is for less round trips (SMTP is a very chatty protocol).

Hope that helps!
