### ISSUE TITLE
NoMethodError: undefined method `settings' for #<SendGridActionMailer::DeliveryMethod:0x0055cc36982d50>

### ISSUE THREAD

**Issue by nitvik** [eddiezane/sendgrid-actionmailer#22]
I got this error, when I was just testing this Gem for the first time.
I made a new Mailer called SendgridMailer and defined a method in that as test_send_email and sent an email to myself. Then I opened rails console and tried sending an email and I got the following error.

Rails version is 4.1.14

```

SendgridMailer.test_send_email.deliver!
  Rendered sendgrid_mailer/test_send_email.html.erb (2.9ms)

SendgridMailer#test_send_email: processed outbound mail in 186.5ms
NoMethodError: undefined method `settings' for #<SendGridActionMailer::DeliveryMethod:0x0055cc36982d50>

```

**Comment by GUI** [comment]
Based on [this thread](https://github.com/aws/aws-sdk-ruby/issues/246#issuecomment-17849159), try calling `.deliver` instead of `.deliver!` (no bang).

It looks like adding compatibility with `.deliver!` should be possible, but it also looks like `.deliver` should generally be the preferred method.

**Comment by nitvik** [comment]
I have found a solution to this when I cloned your gem. That is to define the settings method. I can make a new branch and push it and create a pull request to your repository with the fix, if you would like.

**Comment by chrisconcepcion** [comment]
I have the same issue, @nitvik can you please make a pull request with your solution

**Comment by tyrauber** [comment]
@nitvik, @chrisconcepcion, this has been resolved on master.
