### ISSUE TITLE
DeliveryMethod#settings method is not implemented properly

### ISSUE THREAD

**Issue by h6ah4i** [eddiezane/sendgrid-actionmailer#27]
The `DeliveryMethod#settings` method should return a Hash object which is passed to the constructor. However, current implementation just returns [an empty Hash](https://github.com/eddiezane/sendgrid-actionmailer/blob/8720222/lib/sendgrid_actionmailer.rb#L36).

Current implementation causes an issue when I use `return_response` option which is supported by the [mikel/mail](https://github.com/mikel/mail) gem.

```ruby
> mailer = SMTPActionMailer.new  # this mailer uses SMTP for delivery method
> mailer.mail(...).deliver!
=>  #<Mail::Message: ...
> mailer.mail(..., delivery_method_options: { return_response: true }).deliver!
=> #<Net::SMTP::Response: ...
```

```ruby
> mailer = SendGridActionMailer.new  # this mailer uses sendgrid-actionmailer for delivery method
> mailer.mail(...).deliver!
=>  #<Mail::Message: ...
> mailer.mail(..., delivery_method_options: { return_response: true }).deliver!
=>  #<Mail::Message: ...

# ^^^ THIS SHOULD BE  #<SendGrid::Response: ...
```

In the mikel/mail gem's code, we can see the following code. It invokes `delivery_method.settings` method and checks whether the `:return_response` flag is present.

```ruby
module Mail
  class Message
    ...

    def deliver!
      inform_interceptors
      response = delivery_method.deliver!(self)
      inform_observers
      delivery_method.settings[:return_response] ? response : self
    end

    ...
  end
end
```

source: https://github.com/mikel/mail/blob/6bc16b4bce4fe280b19523c939b14a30e32a8ba4/lib/mail/message.rb#L271

Reference implementation:
https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/smtp.rb

**Comment by tyrauber** [comment]
@h6ah4i Thank you for the pull request and thorough explanation.
