### ISSUE TITLE
Categories containing commas

### ISSUE THREAD

**Issue by skatenerd** [eddiezane/sendgrid-actionmailer#35]
I noticed that, if I send an email that looks like this:
```
      mail(
        to: email,
        subject: subject,
        categories: [{foo: 42, bar: 99}.to_json]
      )
```
This library ends up mangling the API request, because it [splits the categories on commas](https://github.com/eddiezane/sendgrid-actionmailer/blob/dd3999b24fa9e4cb82106ded488665814d727284/lib/sendgrid_actionmailer.rb#L151).  

I want to say right now, I would understand if you said "we dont support this, you are abusing the Categories field".  I am unfortunately dealing with a legacy app that happens to be abusing the Categories field.

If this is something you do think we should support, I'm not sure exactly how it should work.  The Mail library does some weird parsing on the email fields, which means you'd have to do something like `mail['categories'].instance_variable_get(:@unparsed_value)`, which is pretty weird/bad.

And if this isn't something you want to support (I am open to this!) it might be worth adding some documentation to the readme saying "commas are illegal inside of individual categories".

**Comment by tyrauber** [comment]
@skatenerd What categories you are intending / expecting?  Is `categories: [{foo: 42, bar: 99}.to_json]` supposed to be an array of 2 categories? Or a single category encoded as json?  What are the category names on SendGrid?

**Comment by skatenerd** [comment]
@tyrauber It's supposed to be a single category encoded as json.  I don't think our app has any concept of category names.

**Comment by tyrauber** [comment]
@skatenerd  Hmm, for what purpose? I am trying to understand the use case.  Categories are intended to be used in SendGrid to help sort and filter emails sent by Category.  It seems though that you might be using categories for some other purpose? 

Unfortunately Mail is very finicky with extra data and how it is encoded. And while @unparsed_value would work for Mail2.7, it is not supported in Mail 2.5 and 2.6, resulting in errors or platform specific code.  The only way to get hashes to work with mail is to encode and decode them as JSON. But this presents a problem when trying to maintain JSON as opposed to a hash.

If you tell me more about your use case, perhaps we can determine an application appropriate fix?

**Comment by skatenerd** [comment]
Basically, our use case is one where we're abusing `categories`, in a situation where we _should_ just be using `unique_args`.  We're sending data to sendgrid, so that when they hit our webhook endpoint, we have some extra data about the email that was sent.

I think probably the best approach here is to just fix the legacy code, and move over to using `unique_args`

**Comment by tyrauber** [comment]
@skatenerd I think it's actually `custom_args` instead of `unique_args`.   `custom_args` would definitely be a better attribute for that use case. Unfortunately, I think you'll have the same json encoding issues. But if you change your webhook endpoint, to parse all custom_args individually, instead of a single attribute as json, you should get all the data you need.

I am going to close this as it seems to be isolated to your use case, but let me know if you run into additional issues.
