### ISSUE TITLE
Substitutions may not be used with dynamic templating

### ISSUE THREAD

**Issue by thomassnielsen** [eddiezane/sendgrid-actionmailer#37]
gem version: 2.1.0

I'm trying to switch to using the new dynamic templates, but I keep getting `Sendgrid delivery failed with 400 Substitutions may not be used with dynamic templating`  when sending emails. I've tried different options based on the readme (with and without a `dynamic_template_data` object, etc), but I'm basically stuck.

What I've been trying so far:
```rb
mailer.mail(to: email, from: sender_email, template_id: template_id, subject: "test", body: "test").deliver!
```

The docs says that subject and body is optional if it's provided in the template, but that doesn't seem to be the case by default (Unless the docs means providing an ActionMailer template, in which case that should be specified):

```
NoMethodError: undefined method `humanize' for nil:NilClass
from /Users/thomas/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.1/lib/action_mailer/base.rb:880:in `default_i18n_subject'
```

It seems to me that either it doesn't work yet (maybe v3 support isn't fully baked?), or there is some config required that isn't in the readme. I've tried reading the issues for `sendgrid-ruby` as well, and I understand that the status of their SDK and documentation is less than ideal as well.

If anyone could point me in the right direction that would be great. If we figure it out I can make a PR to update the readme with the parts I'm missing.

**Comment by tyrauber** [comment]
Hi @thomassnielsen, thank you for the detailed report.   I think I see the issue based on the error message. It looks like substitutions cannot be used at the same time as a dynamic template. I made a [change](https://github.com/eddiezane/sendgrid-actionmailer/commit/d36645ade920b5953a933c940bce0706971f1789) to allow this, which based on the error message, looks like it broke the new dynamic template functionality.   I created a branch [fix/dynamic_templates](https://github.com/eddiezane/sendgrid-actionmailer/tree/fix/dynamic_templates) to reverse this.  Would you mind testing and confirming resolution?

**Comment by jennapederson** [comment]
I was experiencing the same and this branch does fix the issue. 

Does the readme need updating with this change? I don't fully follow [this](https://github.com/eddiezane/sendgrid-actionmailer#unsubscribe-links) or how to solve that problem when using dynamic templates.

**Comment by tyrauber** [comment]
Hi @jennapederson, Thanks for the confirmation.  Yeah, the Readme should probably be updated to specify that substitutions cannot be used in combination with dynamic templates. I added a note to the readme, merged in and cut a build for 2.2.0.  Thanks for the contribution!

**Comment by shijudevarajan** [comment]
I am still getting the same error.
What I've been trying so far:
```
mail(to: user.email, template_id: '<template_id>')
```
```
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<SendGridActionMailer::DeliveryMethod::SendgridDeliveryError: Sendgrid delivery failed with 400 Substitutions may not be used with dynamic templating>",
  "traces": {
    "Application Trace": [
      {
        "id": 11,
        "trace": "app/controllers/users_controller.rb:8:in `sign_up'"
      }
    ],
    "Framework Trace": [
      {
        "id": 0,
        "trace": "sendgrid-actionmailer (2.2.1) lib/sendgrid_actionmailer.rb:232:in `perform_send_request'"
      },
      {
        "id": 1,
        "trace": "sendgrid-actionmailer (2.2.1) lib/sendgrid_actionmailer.rb:38:in `deliver!'"
      },
      {
        "id": 2,
        "trace": "mail (2.7.1) lib/mail/message.rb:2159:in `do_delivery'"
      },
      {
        "id": 3,
        "trace": "mail (2.7.1) lib/mail/message.rb:260:in `block in deliver'"
      },
      {
        "id": 4,
        "trace": "actionmailer (5.2.3) lib/action_mailer/base.rb:560:in `block in deliver_mail'"
```

**Comment by tyrauber** [comment]
@shijudevarajan I think I see the issue. Can you try the branch fix/template_id_substitutions and confirm the solution. Thanks.

**Comment by shijudevarajan** [comment]
@tyrauber You know what, it worked! So can I point to that branch for my project? Do you have any plan to merge that fix to master any time soon?

**Comment by tyrauber** [comment]
@shijudevarajan Merged. Cut a new build with a minor version bump to 2.3.0.  Lock it to '~> 2.3', bundle update and you should be good to go.
