### ISSUE TITLE
mail_settings cannot be empty hash

### ISSUE THREAD

**Issue by thomassnielsen** [eddiezane/sendgrid-actionmailer#41]
Passing `mail_settings: {}` causes a crash when sending emails.

The error is caused by the [usage of `json_parse` to parse mail settings](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L184). The regex used in [`json_parse`](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L138)  is confused by blank strings, which is what you get calling `mail['mail_settings'].value` when mail_settings is empty.

The code I had when discovering this:

```rb
  def welcome_email
    user = params[:user]
    mail(
      to: user.email,
      template_id: WELCOME_TEMPLATE_ID,
      dynamic_template_data: { name: user.first_name },
      mail_settings: mail_settings
    )
  end


  private

  def mail_settings
    if Rails.env.production?
      {}
    else
      {
        sandbox_mode: {
          enable: true
        }
      }
    end
  end
```

I'm changing my code to this workaround for now:

```rb
  def mail_settings
    {
      sandbox_mode: {
        enable: !Rails.env.production?
      }
    }
  end
```

I'm not sure what the intention of the regex in the `json_parse` method is, so unfortunately I can't attempt a PR at this time.

**Comment by tyrauber** [comment]
Hey @thomassnielsen,  Given the gem passes options through Mail, and Mail treats those attributes as strings, json encoding was required.  The [json_parse](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L184) method was intended to enable ruby hash syntax for mail options, in addition to json.  The ['parse_object' context spec](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/spec/lib/sendgrid_actionmailer_spec.rb#L298-L318) tests this functionality with ruby 1.8, 1.9 and json hashes.

Digging in though, it looks like this is actually an issue with Mail and not the regex in 'json_parse'.    It appears that Mail will not accept an empty hash as an attribute and translates it to nil.
```
 > Mail.new(mail_settings:{})
 => #<Mail::Message:70275845826100, Multipart: false, Headers: <mail-settings: >>
```
As a result, JSON.parse(nil) fails.

PR #42 modifies json_parse to be able to handle nil options.   Does that address the issue?
