### ISSUE TITLE
to field issue Sendgrid delivery failed with 400 The template_id must be a valid GUID

### ISSUE THREAD

**Issue by godzilla74** [eddiezane/sendgrid-actionmailer#47]
Seems that the `to:` field has an issue.  When using a `.each` loop, running into issues, however if it's mapped seems to work fine.  The issue with going the mapped route, is all users show up on the to line in the email:

Works:

```
class LessonMailer < ApplicationMailer
  default from: 'test@test.com
  default body: 'not used'
 
  def new_lesson
    @users = User.all
    mail(to: @users.map(&:email).uniq, template_id: 'xxxx-xxxx-xxxxx-xxxxx-xxxxx')
  end
end
```

Does not work:
```
class LessonMailer < ApplicationMailer
  default from: 'test@test.com
  default body: 'not used'
 
  def new_lesson
    @users = User.all
    @users.each do |u|
      mail(to: u.email, template_id: 'xxxx-xxxx-xxxxx-xxxxx-xxxxx')
    end
  end
end
```

The error:
```
[ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [209ea2f1-0cab-4e6a-a4c1-7fd0a4bdfbb3] Error performing ActionMailer::Parameterized::DeliveryJob (Job ID: 209ea2f1-0cab-4e6a-a4c1-7fd0a4bdfbb3) from Async(mailers) in 507.38ms: SendGridActionMailer::DeliveryMethod::SendgridDeliveryError (Sendgrid delivery failed with 400 The template_id must be a valid GUID, you provided '[#<Mail::Field 0x7fd0ebc8ff78 @name="template-id" @unparsed_value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx" @charset="UTF-8" @field_order_id=100 @field=#<Mail::OptionalField:0x00007fd0ec4cb750 @errors=[], @charset="UTF-8", @name="template-id", @length=nil, @element=nil, @value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx">>, #<Mail::Field 0x7fd0eb7aaa08 @name="template-id" @unparsed_value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx" @charset="UTF-8" @field_order_id=100 @field=#<Mail::OptionalField:0x00007fd0ec4bd010 @errors=[], @charset="UTF-8", @name="template-id", @length=nil, @element=nil, @value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx">>, #<Mail::Field 0x7fd0f186a618 @name="template-id" @unparsed_value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx" @charset="UTF-8" @field_order_id=100 @field=#<Mail::OptionalField:0x00007fd0ec4c2718 @errors=[], @charset="UTF-8", @name="template-id", @length=nil, @element=nil, @value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx">>, #<Mail::Field 0x7fd0ec491230 @name="template-id" @unparsed_value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx" @charset="UTF-8" @field_order_id=100 @field=#<Mail::OptionalField:0x00007fd0ec4d34a0 @errors=[], @charset="UTF-8", @name="template-id", @length=nil, @element=nil, @value="xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx">>]'.):
/Users/me/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sendgrid-actionmailer-2.2.1/lib/sendgrid_actionmailer.rb:232:in `perform_send_request'
/Users/me/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sendgrid-actionmailer-2.2.1/lib/sendgrid_actionmailer.rb:38:in `deliver!'
```

**Comment by tyrauber** [comment]
@godzilla74, If you want to send an email to unique `to:` addresses, where the distribution list isn't public, then the second scenario would definitely be the preferred approach. The first approach would send one email to multiple people as to addressees.

But the error actually suggests it might be related to the template_id:  `Sendgrid delivery failed with 400 The template_id must be a valid GUID, you provided...`. 

Can you confirm the template_id being used is valid?

**Comment by godzilla74** [comment]
@tyrauber Yup, the template is valid.  Works fine with the `.map` method, which I really don't want to do since each user email should be treated separately.

**Comment by tyrauber** [comment]
That is really odd.  I see no reason why each would result in the error.  The error message from SendGrid definitely suggests it is an invalid GUID.  Could an email be nil? in User.all or be unsubscribed or in an ASM group?  I know sendgrid will filter out unsubscribed email addresses resulting in a nil or empty to, but the error message should indicate that, not an invalid GUID.

When you do each, are any emails getting out or is it complaining on the first send?

**Comment by godzilla74** [comment]
@tyrauber I agree.  Printing the email to console with `puts u.email` does show the email address, and it's a new SendGrid account, so no blocking logic on that end there.  I'll try to dive into the gem's source code a little later to see if there is anything that can be modified.  Figured I would try making an issue first to see if there was a simple fix.

**Comment by tyrauber** [comment]
I appreciate it. Fastest way to debug this would be to clone the app and write a test case replicating the scenario. A failure test case would be immensely helpful.   Please keep us posted.

**Comment by Hamdan85** [comment]
Im getting the same error. Is this gem also supposed to work only on legacy?

**Comment by tyrauber** [comment]
That could be the issue. I don't know if legacy templates are supported in the v3 API?  This gem is a wrapper around the official [sendgrid-ruby](https://github.com/sendgrid/sendgrid-ruby) gem, which defaults to Version 3 of the API.  It does look like the sendgrid-ruby can use the v2 API. You could use that gem directly, or [migrate your templates](https://sendgrid.com/docs/ui/sending-email/migrating-from-legacy-templates/).  If you do migrate your templates and that resolves the issue, report back and we can add a note to the documentation about legacy templates.

**Comment by Hamdan85** [comment]
No... actually its working... I just typed the template id wrongly. Thanks and sorry

**Comment by rafaeelaudibert** [comment]
Can you check if it works with the following?
The `each` method was supposed to return the original array, not the array with mails you are trying to generate.

`ruby
  User.all.map do |u|
    mail(to: u.email, template_id: 'xxxx-xxxx-xxxxx-xxxxx-xxxxx')
  end
`

**Comment by tyrauber** [comment]
@rafaeelaudibert, the `each` and `map` method returns an array of the last object in the block, in this case the sole object is the result of mail(). If you added another line at the end of the block with `u`, it would return an array of users.
