### ISSUE TITLE
Support sendgrid-ruby 6.0

### ISSUE THREAD

**Issue by macfanatic** [eddiezane/sendgrid-actionmailer#50]
Is there any reason that the library won't support [sendgrid-ruby version 6](https://rubygems.org/gems/sendgrid-ruby/versions/6.0.0) that was released in June 2019?

It appears in the [project changelog](https://github.com/sendgrid/sendgrid-ruby/blob/master/CHANGELOG.md#600---2019-06-04) that the only breaking change was the removal of `sinatra` for inbound messaging parsing, that this library wouldn't depend upon.

**Comment by tyrauber** [comment]
None. Updated, bumped and pushed in 2.4.0. Thanks for the heads up.

**Comment by macfanatic** [comment]
Absolutely, beat me to even attempting to test and submit a PR for it.

Thanks so much!
