### ISSUE TITLE
Cannot send variables to a template

### ISSUE THREAD

**Issue by tkyol** [eddiezane/sendgrid-actionmailer#52]
Hi there,

I'm struggling to pass variables from my rails app to my Sendgrid template.
Everything else works fine.

Here is the code I'm using:

```
    mail(
      to: @user,
      subject: 'email subject',
      body: 'email body',
      template_id: 'xxx',
      dynamic_template_data:{
        variable_1: 'foo',
        variable_2: 'bar'
      }
    )
```

and I tried all of the following in my template:

```variable_1
:variable_1
-variable_1-
%variable_1%
[variable_1]
variable1
:variable1
-variable1-
%variable1%
[variable1]
Variable1
:Variable1
-Variable1-
%Variable1%
[Variable1]
```
Any idea?

I also tried `unique_args` && `sub`

**Comment by DKarp** [comment]
I have the same issue too

**Comment by DKarp** [comment]
OMG, got it! Inside template need use double curly brackets {{variable_1}}

**Comment by tyrauber** [comment]
Yeah, [Sendgrid uses handlebars for template variables](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/).  I've updated the Readme to reflect that fact.  Thanks for raising this issue.

**Comment by tkyol** [comment]
Awesome! The only one I didn't test haha. Thanks for the feedback @DKarp and for the update @tyrauber
