### ISSUE TITLE
Not all error messages have a body

### ISSUE THREAD

**Issue by dramalho** [eddiezane/sendgrid-actionmailer#61]
Hi all

Unlike what [Sendgrid says](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html)

> "Failed requests will always return an error response, including a response code, a message explaining the reason for the error, and a link to any relevant documentation that may help you troubleshoot the problem."

We're been getting a bodyless `401` - our free dev account has run out of email deliveries. This is fine except that it's blowing up inside the `sendgrid-actionmailer` gem , namely here

```ruby
def perform_send_request(email)
      result = client.mail._('send').post(request_body: email.to_json) # ლ(ಠ益ಠლ) that API
      if result.status_code && result.status_code.start_with?('4')
        message = JSON.parse(result.body).fetch('errors').pop.fetch('message')
```

with

` JSON::ParserError: 767: unexpected token at ''`

I guess testing the body before trying to parse JSON would be ideal

Here's a response object example

```ruby
#<SendGrid::Response:0x000055fdf6b29e00
 @body="",
 @headers=
  {"server"=>["nginx"],
   "date"=>["Fri, 17 Jan 2020 09:58:24 GMT"],
   "content-type"=>["application/json"],
   "content-length"=>["76"],
   "connection"=>["close"],
   "access-control-allow-origin"=>["https://sendgrid.api-docs.io"],
   "access-control-allow-methods"=>["POST"],
   "access-control-allow-headers"=>
    ["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"],
   "access-control-max-age"=>["600"],
   "x-no-cors-reason"=>
    ["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]},
 @status_code="401">
```

**Comment by dramalho** [comment]
lovely, thanks @tyrauber

**Comment by tyrauber** [comment]
Well, that was silly of us to expect an error to return an error message. I've pushed a fix to master. Bumped to 2.4.1.  let us know if that resolves the issue.

**Comment by dramalho** [comment]
the documentation is misleading, they say they *always* return a full error message, but then not really.

totally unexpected, thank you for handling it :)
