### ISSUE TITLE
NoMethodError: undefined method `sendgrid_actionmailer_settings=' for ActionMailer::Base:Class

### ISSUE THREAD

**Issue by coding-bunny** [eddiezane/sendgrid-actionmailer#63]
Is this an intended change with the 2.4.1 version?

**Comment by tyrauber** [comment]
No, lock it to 2.4.0. I'll debug it and push a version bump and yank 2.4.1.  Thanks for the heads up.

**Comment by coding-bunny** [comment]
will do! Thanks for the fast response

**Comment by tyrauber** [comment]
2.4.2 has been pushed and 2.4.1 yanked.  My apologies.
