### ISSUE TITLE
0.2.6 release

### ISSUE THREAD

**Issue by ChrisCoffey** [eddiezane/sendgrid-actionmailer#71]
Hello. I've just started using this gem and noticed that the latest release here on GH is quite out of date relative to what's on RubyGems.

It'd be helpful to keep them in-sync.

**Comment by tyrauber** [comment]
Hi @ChrisCoffey Can you give me an example of how they are out of sync?  The second to last commit on master produced the 2.6 build on rubygems. What am I missing?

**Comment by ChrisCoffey** [comment]
Ahh, apologies for being unclear. I was referring to the git hub releases here: https://github.com/eddiezane/sendgrid-actionmailer/releases. Of which, the most recent release is `0.2.1`.

**Comment by tyrauber** [comment]
Ah I see, no problem. [Cut current release](https://github.com/eddiezane/sendgrid-actionmailer/releases/tag/v2.6.0). Sorry about that.

**Comment by ChrisCoffey** [comment]
Thanks!
