### ISSUE TITLE
Error parsing empty response body 

### ISSUE THREAD

**Issue by davydav** [eddiezane/sendgrid-actionmailer#74]
Hi there ! 

I ran into this exception : `A JSON text must at least contain two octets!` which happens on this line in your code : 
`message = !!(result.body) ? JSON.parse(result.body).fetch('errors').pop.fetch('message') : 'Sendgrid API Error'`

as apparently, some 401 responses from Sendgrid have an empty body...
Moreover, I ran into another 401 saying : 
`Sendgrid delivery failed with 401 Could not authenticate` 
but when I tried again the same operation with the same key it got through... does that ring any bell ?

Anyway thanks for the great work :)

**Comment by tyrauber** [comment]
Hi @davydav, that's odd. !!(result.body) should catch an empty body.  That line was added in #61 to address this exact problem.  Can you confirm you are on version 3.0.0?

**Comment by davydav** [comment]
Yes I am, but I'm also on an old ruby 2.3.1 / rails 4.2.11.1, maybe that's the issue ?

**Comment by tyrauber** [comment]
Possibly? 3.0.0 requires Mail 2.7 as a dependency.  You could try locking sendgrid-actionmailer to version 2.6.0 and see if that resolves the issue.

**Comment by davydav** [comment]
Did some digging, as you can see !!(result.body) returns true in the case of an empty string. Is that behaviour different for you ? 
Again, not to worry, just wanted to let you know :) thanks again !

**Comment by tyrauber** [comment]
hmrph, ok. `!(response.body.empty?)` it is.

Version bump to 3.0.1.  Should resolve this issue. Thanks for digging.

**Comment by tyrauber** [comment]
I'm going to close this. Let me know if you have any additional problems.
