### ISSUE TITLE
NoMethodError:  undefined method `any?' for email address

### ISSUE THREAD

**Issue by adambedford** [eddiezane/sendgrid-actionmailer#79]
We're seeing an error from time to time whereby this library seems to think the value passed to the `to:`  option of the `mail` method is an array. In this case, `add_personalizations` (`sendgrid_actionmailer.rb:178`) is calling `any?` on the `to` value. Since this is a string (only one recipient), it blows up.

I've also seen `each` called on the `to:` value in the past, again indicating that the library expects this value to be an array.

Has anyone else run into this? The short-term fix seems to be `Array(EMAIL_ADDRESS)` but I don't know if that will have different repercussions.

**Comment by tyrauber** [comment]
Hi @adambedford, what version of the Gem are you on? `3.0.2`?  What version of Mail?

On master, `add_personalizations` isn't called until [line 182](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L182) and any? on [line 188](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L188).   I just want to make sure we are looking at the same code.

There are several test cases in the specs that use a single `to:` address. It does get converted to an array in personalizations before being sent to the SendGrid API, but that isn’t blowing up there (at least in the test suite).  Running spec 119 with a debugger at line 178 before and `(mail.to && mail.to.any?)` confirms this.

What are the params being supplied that are resulting in the blow up? To, from, subject? Any additional details? The intermittent nature suggests it is the result of some specific combination of params.

**Comment by adambedford** [comment]
Hey @tyrauber Thanks for digging into this. I'm on `3.0.1` and Mail `2.7.1`. I'm seeing `any?` called on line 184

![image](https://user-images.githubusercontent.com/1626169/82466786-ae0a8e80-9a75-11ea-953f-3545c0edcc09.png)

As far as params go, here's the mailer method that causes the issue in question:

```ruby
class MeetingResponseMailer < ApplicationMailer
  def confirmation_guest(response)
    meeting = response.meeting
    template_data = {
      meeting_response: serialize(response),
      meeting: serialize(meeting)
    }

    mail to: response.email,
         template_id: "d-323b82418dd241ff9b10042518c545a6",
         dynamic_template_data: merge_template_data(template_data)
  end
end

```

`serialize` above is a helper method that just forwards to an instance of a serializer class, basically just slicing certain attributes on the model.

The strange this is I've seen this type of error in two different projects now. At first, it was `each` being called on the email string and now in this project I'm seeing both `any` and `each`.

**Comment by tyrauber** [comment]
@adambedford Are you specifying a body or a default body at the top of the template? Unfortunately due to how ActionMailer works, a body is required.  Although, I would expect that to blow up in an entirely different way.

The intermittent nature of the issue is puzzling.   I wrote a simple spec with just those attributes and the output looks fine (although it is a mock and not a real request), so it is not the params. 

As far as I can tell, mail.to always returns an array, even when supplied a single string.  `mail.to.is_a?(String)` returns false. `mail.to.is_a?(Array)` returns true. Throughout the whole test suite.  There isn't one condition where mail.to is not an array.

One thing we could most certainly do is test that mail.to is an Array, but in the intermittent scenario where that wasn't the case, the personalizations wouldn't be applied. It wouldn't blow up, but it would also mean the email would be sent with partial data which is not optimal. I think in that scenario it is better to err.

Without being able to reliably replicate the conditions I am not sure how we resolve this. I'm stumped.

**Comment by adambedford** [comment]
@tyrauber We're specifying a default body in the `ApplicationMailer`.  I've seen the issue on a couple of different projects now so it makes me think it's developer error but I can't tell what I might be doing wrong. I'll keep an eye out for new occurences and update here as approproate.

**Comment by tyrauber** [comment]
Nor I. Everything looks correct.  One thing we could do is create a branch that wraps the whole personalization block in a begin rescue block and prints the mail object to the logs in the event that it happens again.  That way you could inspect the mail attributes in the logs and determine how to.any? might fail?

If this approach interests you, try the branch [fix/debug_personalizations](https://github.com/eddiezane/sendgrid-actionmailer/tree/fix/debug_personalizations).

```
gem 'sendgrid-actionmailer', :git => "git://github.com/eddiezane/sendgrid-actionmailer", :branch => "fix/debug_personalizations"
```

 Might help in nailing down the exact params that lead to this error.  Thanks for your patience. Wish I had better insight for you.

**Comment by davebream** [comment]
I can confirm the same issue. I've managed to find a specific case that this happens:

```ruby
TestMailer.notification(to: 'Second and Third <test.test@gmail.com>', subject: subject).to => ["test.test@gmail.com"]
TestMailer.notification(to: 'First F, Second and Third <test.test@gmail.com>', subject: subject).to => "First F, Second and Third <test.test@gmail.com>"
```

The second one returns a string which causes this exception to be raised.

**Comment by tyrauber** [comment]
@davebream, I appreciate you tracking down this issue.  That's really odd. I am not entirely sure what's going on here. Why would the second case return a string? I guess that is a bug in Mail or ActionMailler?  

Does switching from `any?` to `!empty?` circumvent the add_personalizations block? We need the add_personalzation block [188-193 to hit](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L188-L193). Would you update the test coverage to ensure that this block is still being executed given the example?

**Comment by davebream** [comment]
@tyrauber Sure, I can add a test case for that. If you look at `to_emails` method, it already handles a case when the input is a string: 
https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L62

and if you do:
```ruby
SendGridActionMailer::DeliveryMethod.new.send(:to_emails, 'First F, Second and Third <test.test@gmail.com>')
```

it returns 
```ruby
[#<SendGrid::Email:0x00007fbb46486238 @email="test.test@gmail.com", @name="First F, Second and Third">]
```

so both `to_emails` and `Email.new` can handle this case well, it looks like only the `.any?` condition that causes errors 😉

**Comment by tyrauber** [comment]
Good enough for me!  Thanks for the fix.
