### ISSUE TITLE
Error message: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by RubenGram** [eddiezane/sendgrid-actionmailer#86]
Hello, I'm trying to use this gem but I get this error message `A JSON text must at least contain two octets!` when I use the Action Mailer deliver_now method. I'm using a mailer, a template and calling it from a controller as usual, testing in development environment. I have no idea about the possible causes, any idea?

More details:
`Completed 500 Internal Server Error in 990ms (ActiveRecord: 4.4ms)

JSON::ParserError - A JSON text must at least contain two octets!:
  json (1.8.6) lib/json/common.rb:155:in `initialize'
  json (1.8.6) lib/json/common.rb:155:in `new'
  json (1.8.6) lib/json/common.rb:155:in `parse'
  sendgrid-actionmailer (2.4.2) lib/sendgrid_actionmailer.rb:231:in `perform_send_request'
  sendgrid-actionmailer (2.4.2) lib/sendgrid_actionmailer.rb:38:in `deliver!'
  mail (2.6.3) lib/mail/message.rb:252:in `deliver!'
  actionmailer (4.2.1) lib/action_mailer/message_delivery.rb:77:in `deliver_now!'
  app/controllers/prospects_controller.rb:605:in `test_mailing'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  sentry-raven (2.7.4) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  activesupport (4.2.1) lib/active_support/callbacks.rb:441:in `instance_exec'
  activesupport (4.2.1) lib/active_support/callbacks.rb:441:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.1) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (1.0.0) lib/mini_profiler/profiling_methods.rb:104:in `block in profile_method'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'`

**Comment by tyrauber** [comment]
Hi @RubenGram, not entirely sure based on the stack trace, but it looks like perhaps the api request to sendgrid failed and they are returning non-valid json. (It shouldn't err out, but that is the only place I see JSON.parse in the codebase.) Unfortunately, SendGrid has a habit of sending error messages as JSON most of the time, and sometime null responses. I have made a branch that simplifies this and returns whatever error sendgrid responds with.  If you want to use that branch instead (fix/simply_error) it might give you better visibility as to what the problem might be.

**Comment by RubenGram** [comment]
@tyrauber I don´t know yet the exact problem but apparently it is related to the API key configuration. I set full access to every feature (alerts, category management, IP management, etc) from sendgrid api keys settings and it worked fine, then I return to normal (only full access to API keys) and still works.

**Comment by tyrauber** [comment]
Hmm, Ok, I wondered if it might be related to authorization. Thanks for reporting back.
