### ISSUE TITLE
emails not delivered - 400 bad request

### ISSUE THREAD

**Issue by ericplezi** [eddiezane/sendgrid-actionmailer#94]
I’m using sendgrid-actionmailer gem with those dependencies (also tested without)

```
gem 'sendgrid', '1.2.4'
gem 'sendgrid-ruby', '6.1.2'
gem 'sendgrid-actionmailer', '3.0.0'
```

I'm struggling with using SendGrid v3; my emails keep not being delivered, I keep receiving a 400 bad request, especially when there are special characters inside it (there are two special characters in the footer. When I remove them, the email is delivered successfully)

Do you have any what I could be doing wrong?

Appreciate the help

**Comment by muhrizkiakbar** [comment]
i found this issue too, so what do you do to fix this issue ?
