### ISSUE TITLE
Bcc extension for multiple addresses

### ISSUE THREAD

**Issue by RubenGram** [eddiezane/sendgrid-actionmailer#96]
Hello, I’m using sendgrid-actionmailer gem and I need to use the bcc extension to send copies of an email to multiple recipients; however I'm not sure of how to do it since the documentation only shows the object for a single recipient:
`mail(to: 'example@email.com', subject: 'email subject', body: 'email body', mail_settings: { bcc: { enable: true, email: 'bcc@example.com' }})`

So, for multiple recipients should I use an array of strings, something like:
`mail(to: 'example@email.com', subject: 'email subject', body: 'email body', mail_settings: { bcc: { enable: true, email: ['bcc1@example.com', 'bcc2@example.com', 'bcc3@example.com'] }})`

Or maybe just a string made of comma-separated addresses, something like:
`mail(to: 'example@email.com', subject: 'email subject', body: 'email body', mail_settings: { bcc: { enable: true, email: 'bcc1@example.com, bcc2@example.com, bcc3@example.com' }})`

Or maybe an array of objects. Well, I hope you can help me, thanks.

**Comment by tyrauber** [comment]
Hey @RubenGram, that's definitely confusing.  `mail_settings` should be used for configuration options passed to the initializer or mail object.   The ability to pass a bcc address to mail_settings probably exists for the purpose of globally bccing an address.

For more, flexible sending options, such as BCCing multiple people, [use personalizations](https://github.com/eddiezane/sendgrid-actionmailer#personalizations-json). The following should get you there.

```
mail(subject: 'default subject', 'email body', personalizations: [
  { bcc: [{ email: 'example@example.com' }]},
  { bcc: [{ email: 'example2@example.com' }]}
])
```


use personalizations, not mail_settings. mail_settings
