### ISSUE TITLE
Clarify how to test

### ISSUE THREAD

**Issue by ur5us** [eddiezane/sendgrid-actionmailer#98]
Using something like 

```ruby
self.sendgrid_actionmailer_settings = {
  api_key: ENV["SENDGRID_API_KEY"],
  perform_send_request: !Rails.env.test?,
  return_response: Rails.env.test?
}
```

should I be able to `expect(ActionMailer::Base.deliveries.size).to eq(1)`?

**Comment by tyrauber** [comment]
That is a really good question! I would assume so, as [setting perform_send_request to false just skips the api call to sendgrid](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L37-L41). If false, [return_response true would return the mail attributes while return_response false would return the DeliveryMethod class instance](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L43). Either way, I'd expect Mail/ActionMailer to behave as expected? Does it not?

You could also try using SendGrid's Sandbox Mode:

```
config.action_mailer.sendgrid_actionmailer_settings = {
  api_key: ENV['SENDGRID_API_KEY'],
  mail_settings: { sandbox_mode: { enable: Rails.env.test? }}
}
```

**Comment by ur5us** [comment]
@tyrauber Currently it does not behave as expected as far as I can tell. 

> You could also try using SendGrid's Sandbox Mode

Sure but the sandbox mode is an orthogonal feature/concern IMO. It’s an integration/system test actually involving hitting a 3rd party. There’s certainly value in that. But here I’m trying to test a system without hitting 3rd parties as email delivery itself is not the main concern of the test. The test scenario only needs to validate that an email is “triggered” which is what I put in my example:

```ruby
expect(ActionMailer::Base.deliveries.size).to eq(1)
```

I’ll try to provide a little Rails example app to highlight the issue. I looked at the code of this gem but nothing stood out that would cause the issue.

**Comment by jaredsohn** [comment]
@ur5us Did you find a solution?

If the gem doesn't provide a flag to not send you can always use vcr or do other request mocking, although that requires a bit of work when switching from action mailer.

**Comment by jaredsohn** [comment]
@ur5us When using sendgrid via smtp we would set action_mailer.delivery_method to test when running tests; works fine when I keep that.

```
  # Tell Action Mailer not to deliver emails to the real world.
  # The :test delivery method accumulates sent emails in the
  # ActionMailer::Base.deliveries array.
  config.action_mailer.delivery_method = :test
```

**Comment by ur5us** [comment]
@jaredsohn Yes, I have that line in my `config/environments/test/rb` file. Yet, this was a good hint as to why it wasn’t working **for my setup**. Currently, that particular app uses a dual approach to sending emails due to historical reasons, i.e. emails with templates (HTML/text) generated by Rails and emails using Sendgrid’s dynamic templates. Thus, I have the following 2 mailers:

```ruby
class BookingMailer < ApplicationMailer
  # …
end

class SendgridBookingMailer < ApplicationMailer
  self.delivery_method = :sendgrid_actionmailer
  # …
end
```

The issue was that `self.delivery_method` was always set to `:sendgrid_actionmailer` ), thus ignoring `config.action_mailer.delivery_method` from `config/environments/test.rb`. I have now changed that to `self.delivery_method = Rails.env.test? ? Rails.application.config.action_mailer.delivery_method : :sendgrid_actionmailer` and all is good. 

@tyrauber Thanks for your assistance also. 

Apologies for not realizing that it was my specific setup. Thus, I think it’s safe to close this issue.
