### ISSUE TITLE
undefined method `unparsed_value' for #<Mail::OptionalField:0x0055bc96f25960>

### ISSUE THREAD

**Issue by somiryu** [eddiezane/sendgrid-actionmailer#99]
Hi. I'm trying to send a mail like this:

mail( :to => "ignore@ignome.com",
    :subject => subject, categories: ["Newsletter"],
    personalizations: [
      {to: [{email: "mail1@mail.com"}]},
      {to: [{email: "mail2@mail.com"}]},
    ])

But I receive the error in the title. I only happens when I add personalizations. I'm not using rails 5.0. Is there a workaround?

**Comment by tyrauber** [comment]
Hi @somiryu, can you confirm you are on the current version of the gem. Also, if you could share a full stack trace that would be helpful. Specifically, which Mail::OptionalField is throwing this error.

**Comment by somiryu** [comment]
Hi! I updated to rails 5 and it worked like a charm. I think this was the push I needed to make the update. Still, if this can be helpful, in rails 4.2 it raises two errors:

return true if elm&.dig(:email) == additonal_mail 
I think I solved it by changing it for elm[:email] == additional_mail

With that I was able to send a mail with the simple fields (:to, :subject) and I think with :categories as well. The error was raised when I added the OptionalField :personalizations. I think uparsed_valuechanged its behavior in rails 5. So then gem could be usable in rails 4 with the above change, but not with personalizations at least.

Thanks for the reply!

**Comment by mountriv99** [comment]
Hi I'm still getting this when trying it out in the console with "custom_args" (works if i remove custom_args)


```
	def sendgrid_test(to_email)
		mail(:to => to_email, :subject => "Test", custom_args: {campaign: 'welcome'}) do |format|
			format.text { render :plain => "Test message" }
		end
	end
```


```
irb(main):027:0> ApplicationMailer.sendgrid_test("xxx@xxx.com").deliver_now
  Rendering text template
  Rendered text template (0.1ms)
ApplicationMailer#sendgrid_test: processed outbound mail in 22.7ms
Sent mail to xxx@xxx.com (8.9ms)
Date: Wed, 16 Feb 2022 18:45:23 +0800
From: XXX <no-reply@xxx.com>
To: xxx@xxx.com
Message-ID: <620cd5c3142c2_e78c3fde1243193c94884@MacBook-Air-2.local.mail>
Subject: Test
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
custom-args: {:campaign=>"welcome"}
X-SMTPAPI: {"category":"dev","filters":{"clicktrack":{"settings":{"enable":0}}}}

Test message
NoMethodError: undefined method 'unparsed_value' for #<Mail::OptionalField:0x007fbc2ad7b318>
	from (irb):27
```


Rails 5.1.6
ruby 2.3.1p112
sendgrid-actionmailer-3.2.0
